### ISSUE TITLE
Support for Contao 4.13

### ISSUE THREAD

**Issue by contaoacademy** [contao/mobile-page-layout-bundle#6]
I added the extension on a Contao 4.13 installation. The installation was possible, but then it comes to an error.
Is the package still maintained and should work under Contao 4.13?
Error message comes with PHP 7.4 and PHP 8.1  

`[2022-07-26T21:30:06.842471+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to Contao\MobilePageLayoutBundle\EventListener\ToggleViewListener::onKernelRequest() must be an instance of Symfony\Component\HttpKernel\Event\GetResponseEvent, instance of Symfony\Component\HttpKernel\Event\RequestEvent given, called in /demo_latest/vendor/symfony/event-dispatcher/EventDispatcher.php on line 270" at /demo_latest/vendor/contao/mobile-page-layout-bundle/src/EventListener/ToggleViewListener.php line 43 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Contao\\MobilePageLayoutBundle\\EventListener\\ToggleViewListener::onKernelRequest() must be an instance of Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent, instance of Symfony\\Component\\HttpKernel\\Event\\RequestEvent given, called in /demo_latest/vendor/symfony/event-dispatcher/EventDispatcher.php on line 270 at /demo_latest/vendor/contao/mobile-page-layout-bundle/src/EventListener/ToggleViewListener.php:43)"} []`

**Comment by kikmedia** [comment]
Exactly the same error here, tested with PHP 8.1 (and skipped PHP 7).

**Comment by ausi** [comment]
Does everything else from the bundle work if you change the following line: https://github.com/contao/mobile-page-layout-bundle/blob/7d4a427945b942dfb9fa9f6d68b6291331397322/src/EventListener/ToggleViewListener.php#L43 to this one?

```php
public function onKernelRequest($event): void
```

**Comment by ausi** [comment]
> Is the package still maintained and should work under Contao 4.13?

IMO yes, we should fix it so that it works with Contao 4.13. (But probably not with 5.0).

**Comment by kikmedia** [comment]
Unfortunately only partially, and now I get another one for the DisableCacheListener:

`[2022-08-02T08:59:42.953089+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Contao\MobilePageLayoutBundle\EventListener\DisableCacheListener::onKernelResponse(): Argument #1 ($event) must be of type Symfony\Component\HttpKernel\Event\FilterResponseEvent, Symfony\Component\HttpKernel\Event\ResponseEvent given, called in /usr/www/users/myuser/temp/mysite/contao4.13/vendor/symfony/event-dispatcher/EventDispatcher.php on line 270" at /usr/www/users/myuser/temp/mysite/contao4.13/vendor/contao/mobile-page-layout-bundle/src/EventListener/DisableCacheListener.php line 20 {"exception":"[object] (TypeError(code: 0): Contao\\MobilePageLayoutBundle\\EventListener\\DisableCacheListener::onKernelResponse(): Argument #1 ($event) must be of type Symfony\\Component\\HttpKernel\\Event\\FilterResponseEvent, Symfony\\Component\\HttpKernel\\Event\\ResponseEvent given, called in /usr/www/users/myuser/temp/mysite/contao4.13/vendor/symfony/event-dispatcher/EventDispatcher.php on line 270 at /usr/www/users/myuser/temp/mysite/contao4.13/vendor/contao/mobile-page-layout-bundle/src/EventListener/DisableCacheListener.php:20)"} []`

So I changed that too in https://github.com/contao/mobile-page-layout-bundle/blob/7d4a427945b942dfb9fa9f6d68b6291331397322/src/EventListener/DisableCacheListener.php#L20 from
`public function onKernelResponse(FilterResponseEvent $event): void`
to
`public function onKernelResponse($event): void`
and voilá, I'm able to call the install tool.

But this leads to another error, this time in Contao itself. After calling a page in backend, I get `Attempted to call an undefined method named "getPageLayouts" of class "tl_page".` In my log file, this one shows up with

`[2022-08-02T09:24:15.323122+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "getPageLayouts" of class "tl_page"." at /usr/www/users/myuser/temp/mysite/contao4.13/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php line 1319 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"getPageLayouts\" of class \"tl_page\". at /usr/www/users/myuser/temp/mysite/contao4.13/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:1319)"} []`

Hmm, this could be because of some older extensions (this is an ancient installation, coming from Contao 3.2, with tons of possibly unwanted stuff), I will check that out. In the meantime, maybe someone tries to get the second patched line to work?

**Comment by ausi** [comment]
> Hmm, this could be because of some older extensions

No, I had the same issue in a clean installation. 

The pull request #7 should fix all issues I think, can you verify these fixes?

**Comment by kikmedia** [comment]
Works for me. Thanks!

**Comment by ausi** [comment]
Closed in favor of #7
